"""add engineering material core

Revision ID: 5c97e2fd405e
Revises: bee771ab1c79
Create Date: 2026-06-28 15:41:22.008443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c97e2fd405e'
down_revision: Union[str, Sequence[str], None] = 'bee771ab1c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color_hex', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('material_families', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_families_slug'), ['slug'], unique=True)

    op.create_table('property_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('value_type', sa.String(length=40), nullable=False),
    sa.Column('default_unit', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_definitions_key'), ['key'], unique=True)

    op.create_table('material_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('short_name', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=260), nullable=False),
    sa.Column('classification', sa.String(length=120), nullable=False),
    sa.Column('formula', sa.String(length=300), nullable=False),
    sa.Column('repeat_unit', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('best_for', sa.Text(), nullable=False),
    sa.Column('avoid_for', sa.Text(), nullable=False),
    sa.Column('source_notes', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['material_families.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_variants_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_variants_slug'), ['slug'], unique=True)

    op.create_table('material_property_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_variant_id', sa.Integer(), nullable=False),
    sa.Column('property_definition_id', sa.Integer(), nullable=False),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_min', sa.Float(), nullable=True),
    sa.Column('value_max', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=80), nullable=False),
    sa.Column('material_state', sa.String(length=40), nullable=False),
    sa.Column('test_condition', sa.Text(), nullable=False),
    sa.Column('test_standard', sa.String(length=160), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('source_title', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('confidence', sa.String(length=40), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_variant_id'], ['material_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_definition_id'], ['property_definitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_property_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_property_records_material_variant_id'), ['material_variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_property_records_property_definition_id'), ['property_definition_id'], unique=False)
        batch_op.create_index('ix_material_property_records_variant_property', ['material_variant_id', 'property_definition_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_property_records', schema=None) as batch_op:
        batch_op.drop_index('ix_material_property_records_variant_property')
        batch_op.drop_index(batch_op.f('ix_material_property_records_property_definition_id'))
        batch_op.drop_index(batch_op.f('ix_material_property_records_material_variant_id'))

    op.drop_table('material_property_records')
    with op.batch_alter_table('material_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_variants_slug'))
        batch_op.drop_index(batch_op.f('ix_material_variants_family_id'))

    op.drop_table('material_variants')
    with op.batch_alter_table('property_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_definitions_key'))

    op.drop_table('property_definitions')
    with op.batch_alter_table('material_families', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_families_slug'))

    op.drop_table('material_families')
    # ### end Alembic commands ###
