"""baseline prototype schema

Revision ID: bee771ab1c79
Revises: 
Create Date: 2026-06-28 15:26:43.498077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee771ab1c79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=260), nullable=False),
    sa.Column('family', sa.String(length=120), nullable=False),
    sa.Column('subfamily', sa.String(length=80), nullable=False),
    sa.Column('family_color', sa.String(length=16), nullable=False),
    sa.Column('formula', sa.String(length=300), nullable=False),
    sa.Column('repeat_unit', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('best_for', sa.Text(), nullable=False),
    sa.Column('avoid_for', sa.Text(), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('properties_json', sa.Text(), nullable=False),
    sa.Column('source_notes', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_family'), ['family'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_slug'), ['slug'], unique=True)

    op.create_table('filament_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('product_name', sa.String(length=180), nullable=False),
    sa.Column('supplier', sa.String(length=160), nullable=False),
    sa.Column('url', sa.String(length=800), nullable=False),
    sa.Column('color_name', sa.String(length=80), nullable=False),
    sa.Column('spool_weight_g', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filament_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filament_products_material_id'), ['material_id'], unique=False)

    op.create_table('price_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price_eur', sa.Float(), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=False),
    sa.Column('source_label', sa.String(length=160), nullable=False),
    sa.Column('stock_note', sa.String(length=240), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['filament_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_entries_product_id'), ['product_id'], unique=False)

    op.create_table('print_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('profile_name', sa.String(length=180), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('nozzle_diameter', sa.Float(), nullable=False),
    sa.Column('nozzle_temp', sa.Float(), nullable=False),
    sa.Column('bed_temp', sa.Float(), nullable=False),
    sa.Column('chamber_temp', sa.Float(), nullable=False),
    sa.Column('speed_mm_s', sa.Float(), nullable=False),
    sa.Column('dryer_temp', sa.Float(), nullable=False),
    sa.Column('dryer_hours', sa.Float(), nullable=False),
    sa.Column('build_plate', sa.String(length=140), nullable=False),
    sa.Column('result_rating', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('printed_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['filament_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_profiles_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_profiles_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_profiles_product_id'))
        batch_op.drop_index(batch_op.f('ix_print_profiles_material_id'))

    op.drop_table('print_profiles')
    with op.batch_alter_table('price_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_entries_product_id'))

    op.drop_table('price_entries')
    with op.batch_alter_table('filament_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filament_products_material_id'))

    op.drop_table('filament_products')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_slug'))
        batch_op.drop_index(batch_op.f('ix_materials_family'))

    op.drop_table('materials')
    # ### end Alembic commands ###
